export type LifeEntry = {
  id: string;
  title: string;
  category: "DOG" | "PLACE" | "CAT";
  group: "dogs" | "places" | "courtyard";
  caption: string;
  image: string;
  alt: string;
  width: number;
  height: number;
};

export const lifeEntries: LifeEntry[] = [
  {
    id: "01",
    title: "Xiaopang & Xiaoshou",
    category: "DOG",
    group: "dogs",
    caption: "At the very beginning.",
    image: "/life/01-pang-shou-puppies.jpg",
    alt: "Xiaopang and Xiaoshou lying together as puppies",
    width: 640,
    height: 478,
  },
  {
    id: "02",
    title: "Xiaosan",
    category: "DOG",
    group: "dogs",
    caption: "Close enough to fill the frame.",
    image: "/life/02-xiaosan-closeup.jpg",
    alt: "A close portrait of Xiaosan resting on a floral pillow",
    width: 1279,
    height: 1706,
  },
  {
    id: "03",
    title: "Xiaopang",
    category: "DOG",
    group: "dogs",
    caption: "A quiet afternoon by the window.",
    image: "/life/03-xiaopang-window.jpg",
    alt: "Xiaopang sitting beside a sunlit window",
    width: 1279,
    height: 1706,
  },
  {
    id: "04",
    title: "Xiaopang",
    category: "DOG",
    group: "dogs",
    caption: "At home, watching the room.",
    image: "/life/04-xiaopang-home.jpg",
    alt: "Xiaopang resting on a blue sofa at home",
    width: 1279,
    height: 1706,
  },
  {
    id: "05",
    title: "Xiaosan",
    category: "DOG",
    group: "dogs",
    caption: "The familiar look from the hallway.",
    image: "/life/05-xiaosan-hallway.jpg",
    alt: "Xiaosan looking up in a hallway",
    width: 1279,
    height: 1706,
  },
  {
    id: "06",
    title: "Xiaoshou",
    category: "DOG",
    group: "dogs",
    caption: "A yellow coat and a patient gaze.",
    image: "/life/06-xiaoshou-sofa.jpg",
    alt: "Xiaoshou lying on a green sofa",
    width: 1279,
    height: 1706,
  },
  {
    id: "07",
    title: "Xiaosan",
    category: "DOG",
    group: "dogs",
    caption: "Camera curious, as always.",
    image: "/life/07-xiaosan-young.jpg",
    alt: "A young Xiaosan looking closely into the camera",
    width: 810,
    height: 1080,
  },
  {
    id: "08",
    title: "Evening clouds",
    category: "PLACE",
    group: "places",
    caption: "Warm light above the railway.",
    image: "/life/08-evening-clouds.jpg",
    alt: "Warm evening clouds above a railway and distant hills",
    width: 1706,
    height: 1279,
  },
  {
    id: "09",
    title: "Between rail and sea",
    category: "PLACE",
    group: "places",
    caption: "A blue horizon framed by the station.",
    image: "/life/09-station-sea.jpg",
    alt: "A coastal view from a railway station platform",
    width: 1706,
    height: 1279,
  },
  {
    id: "10",
    title: "Violet corridor",
    category: "PLACE",
    group: "places",
    caption: "Dusk caught between two buildings.",
    image: "/life/10-violet-sky.jpg",
    alt: "A violet dusk sky framed by campus buildings",
    width: 1279,
    height: 1706,
  },
  {
    id: "11",
    title: "After class",
    category: "PLACE",
    group: "places",
    caption: "The campus turning pink at sunset.",
    image: "/life/11-campus-sunset.jpg",
    alt: "A pink sunset over a campus road",
    width: 1706,
    height: 1279,
  },
  {
    id: "12",
    title: "Palm silhouettes",
    category: "PLACE",
    group: "places",
    caption: "The last colour reflected on the lake.",
    image: "/life/12-palms-dusk.jpg",
    alt: "Palm trees silhouetted against a pink evening sky",
    width: 1706,
    height: 1279,
  },
  {
    id: "13",
    title: "A bright day",
    category: "PLACE",
    group: "places",
    caption: "Clouds gathering above the campus.",
    image: "/life/13-campus-clouds.jpg",
    alt: "A bright campus landscape beneath large summer clouds",
    width: 1706,
    height: 1279,
  },
  {
    id: "14",
    title: "Courtyard visitor",
    category: "CAT",
    group: "courtyard",
    caption: "One of the cats that made the garden their own.",
    image: "/life/14-courtyard-cat.jpg",
    alt: "A pale orange and white cat visiting the courtyard",
    width: 1279,
    height: 1706,
  },
];
