import Image from "next/image";
import SiteFrame from "../../components/SiteFrame";
import { featuredProject } from "../../../content/projects";

const stages = [
  ["01", "ASK", "A learner question enters one course-scoped workflow."],
  ["02", "GROUND", "RAG passages and graph relationships supply traceable context."],
  ["03", "RESPOND", "Dify coordinates the route while the backend validates and streams the answer."],
  ["04", "ADAPT", "Attempts update BKT mastery, which shapes the next report, exercise and learning path."],
];

const evidence = [
  {
    src: "/project-demos/ai-teaching-assistant/process-02-dify-workflow.png",
    alt: "Original Dify workflow used by the AI teaching assistant",
    label: "WORKFLOW",
    title: "The actual Dify orchestration canvas",
    detail: "Intent routing, retrieval, graph lookup and answer generation are connected in one visible workflow.",
  },
  {
    src: "/project-demos/ai-teaching-assistant/process-04-kg-query.png",
    alt: "Original graph query and result for the course knowledge graph",
    label: "KNOWLEDGE",
    title: "A real course-graph query",
    detail: "The query returns the hierarchy used for prerequisite-aware explanations and study paths.",
  },
  {
    src: "/project-demos/ai-teaching-assistant/process-06-learning-report.png",
    alt: "Original learning report generated by the AI teaching assistant",
    label: "LEARNER STATE",
    title: "Mastery becomes a usable learning report",
    detail: "Attempts, weak topics and mastery values are translated into concrete next actions.",
  },
];

const responsibilities = [
  "Led planning, task allocation and cross-module integration for the project team.",
  "Built the Dify workflows and connected retrieval, graph context and model calls.",
  "Defined database fields, API contracts and payloads shared between services.",
  "Built the early Apache AGE knowledge-graph schema and query prototype.",
  "Configured HTTP nodes and supported end-to-end integration and debugging.",
];

const stack = [
  ["ORCHESTRATION", "Dify · GPT-4o"],
  ["EVIDENCE", "RAG · text-embedding-3-large · gte-rerank-v2"],
  ["KNOWLEDGE", "Apache AGE · openCypher"],
  ["APPLICATION", "Node.js · TypeScript · React · SSE"],
  ["STATE", "PostgreSQL · Bayesian Knowledge Tracing"],
];

export default function TeachingAssistantCaseStudy() {
  return (
    <SiteFrame active="work">
      <article className="case-study-page">
        <header className="case-study-hero">
          <div className="case-study-hero-copy">
            <div className="case-study-kicker">
              <span>CASE STUDY / 01</span>
              <span>{featuredProject.category}</span>
            </div>
            <p className="case-study-overline">KNOWLEDGE-ENHANCED LEARNING SYSTEM</p>
            <h1>AI Teaching<br /><em>Assistant.</em></h1>
            <p className="case-study-standfirst">
              A course-grounded learning system that connects retrieval, a domain
              knowledge graph and persistent learner mastery instead of treating
              every question as an isolated chat.
            </p>
            <dl className="case-study-facts">
              <div><dt>YEAR</dt><dd>{featuredProject.year}</dd></div>
              <div><dt>ROLE</dt><dd>PROJECT LEAD · WORKFLOW ENGINEER</dd></div>
              <div><dt>OUTCOME</dt><dd>4 CONNECTED LEARNING WORKFLOWS</dd></div>
            </dl>
          </div>
          <figure className="case-study-hero-visual">
            <Image
              src="/project-demos/ai-teaching-assistant/process-01-system-interface.png"
              alt="Original running interface of the AI teaching assistant"
              width={1600}
              height={900}
              priority
              sizes="(max-width: 900px) 100vw, 48vw"
            />
            <figcaption>01 / ORIGINAL RUNNING SYSTEM INTERFACE</figcaption>
          </figure>
        </header>

        <section className="case-study-overview">
          <span>01 / THE PROBLEM</span>
          <div>
            <h2>Answers needed evidence.<br />Learning needed continuity.</h2>
            <p>
              A useful teaching assistant has to do more than retrieve a paragraph.
              It must understand course structure, remember what a learner has
              mastered and turn each interaction into a better next step.
            </p>
            <div className="case-study-metrics" aria-label="Project summary">
              <div><strong>3</strong><span>EVIDENCE LAYERS<br />TEXT · GRAPH · STATE</span></div>
              <div><strong>4</strong><span>STUDENT ROUTES<br />Q&amp;A · PRACTICE · REPORT · PATH</span></div>
              <div><strong>1</strong><span>SHARED<br />LEARNER MODEL</span></div>
            </div>
          </div>
        </section>

        <section className="case-study-method">
          <header>
            <span>02 / HOW IT WORKS</span>
            <h2>One question.<br />One learning loop.</h2>
          </header>
          <ol>
            {stages.map(([number, title, detail]) => (
              <li key={number}>
                <span>{number}</span>
                <strong>{title}</strong>
                <p>{detail}</p>
              </li>
            ))}
          </ol>
        </section>

        <section className="case-study-proof">
          <header>
            <span>03 / PROCESS EVIDENCE</span>
            <h2>Built, queried<br />and observed.</h2>
            <p>Three checkpoints show the system moving from orchestration to structured knowledge and learner-facing output.</p>
          </header>
          <div className="case-study-proof-grid">
            {evidence.map((item, index) => (
              <figure className={index === 0 ? "is-featured" : ""} key={item.src}>
                <div>
                  <Image src={item.src} alt={item.alt} width={1600} height={900} sizes="(max-width: 760px) 100vw, 50vw" />
                </div>
                <figcaption>
                  <span>0{index + 1} / {item.label}</span>
                  <strong>{item.title}</strong>
                  <p>{item.detail}</p>
                </figcaption>
              </figure>
            ))}
          </div>
        </section>

        <section className="case-study-contribution">
          <div>
            <span>04 / MY CONTRIBUTION</span>
            <h2>Project lead,<br /><em>workflow engineer.</em></h2>
            <p>
              This was a team project. My work sat at the boundaries between AI
              orchestration, graph knowledge, application APIs and learner state.
            </p>
            <ul>
              {responsibilities.map((item) => <li key={item}>{item}</li>)}
            </ul>
          </div>
          <aside className="case-study-ledger">
            <span>TECHNOLOGY LEDGER</span>
            <dl>
              {stack.map(([label, detail]) => (
                <div key={label}><dt>{label}</dt><dd>{detail}</dd></div>
              ))}
            </dl>
            <a href="https://www.zcst-ai-assistant.online/login" target="_blank" rel="noreferrer">
              OPEN TEAM SYSTEM · LOGIN REQUIRED <span>↗</span>
            </a>
          </aside>
        </section>
      </article>
    </SiteFrame>
  );
}
